import type { NextPage } from "next";
import Head from "next/head";

const Meta: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bell Test page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Meta;
